### ISSUE TITLE
Textes avec annotations

### ISSUE THREAD

**Issue by Ninroot** [Ninroot/phi#5]
Comment rendre les annotations d'articles plus jolies? Changer le type de markdown?

**Comment by s-mick** [comment]
Il n'y a pas moyen d'intégrer des hyperliens internes, ou des notes de bas de page ? Je connais pas trop le MarkDown façon GitHub, mais il me semble qu'il est un peu plus étendu que des versions implémentées sur d'autres plateformes (je pense en particulier à Dillinger et Discord).

Si tu connais une solution technique qui permet de changer la syntaxe même du formatage de texte, je pense qu'on peut aller vers des syntaxes plus riches, type Wikia ou même RST.

**Comment by Ninroot** [comment]
La configuration par défaut est du  `kramdowm`. Ce type permet de faire des annotations 😉
