### ISSUE TITLE
Branche « suggestions » vide ?

### ISSUE THREAD

**Issue by s-mick** [Ninroot/phi#7]
J'allais contribuer sur la branche `suggestions` mais je suis tombé sur une 404 de GitHub… J'ai l'impression qu'elle est vide. C'est une relique des temps anciens ? Faut-il la supprimer ?

Pour l'instant, je compte essentiellement contribuer sur la forme plutôt que le fond : relecture, correction de fautes typographiques, légères reformulations et compagnie. Il vaut mieux que je travaille sur la branche `brouillon` ou je me permets de travailler sur `master` directement ?

**Comment by Ninroot** [comment]
> J'allais contribuer sur la branche suggestions mais je suis tombé sur une 404 de GitHub… J'ai l'impression qu'elle est vide. C'est une relique des temps anciens ? Faut-il la supprimer ?

Je viens de faire un peu de ménage avec les anciennes branches (`suggestions` et `gh-pages`). Jette un oeil à `git fetch -p` si besoin.

> Pour l'instant, je compte essentiellement contribuer sur la forme plutôt que le fond : relecture, correction de fautes typographiques, légères reformulations et compagnie. Il vaut mieux que je travaille sur la branche brouillon ou je me permets de travailler sur master directement ?

Chouette ! Je travaille actuellement sur la branche `brouillon`, je te conseille plutôt de créer une branche `relecture` qu'on pourra merge puis suppr. Si tu souhaites participer plus longuement je te propose de créer ta propre branche de brouillon.
